version: '3.5'

services:
  # Elasticsearch container
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    volumes:
      # Persist data between instances standup/teardown
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    ports:
      - '49300:9300'
      - '49200:9200'
    networks:
      backend:
        aliases:
          - elasticsearch
volumes:
  esdata:

networks:
  backend:
    external:
      name: backend_network
