version: '3.5'

services:

  # react front end
  frontend:
    container_name: search-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image:
      search-frontend:latest
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '43000:3000'
    environment:
      - NODE_ENV=development

  # flask back end
  backend:
    container_name: flask-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image:
      flask-backend:latest
    volumes:
      - './backend/usr/src/app'
    ports:
      - '45000:80'

  
  # Elasticsearch container
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    volumes:
      # Persist data between instances standup/teardown
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    ports:
      - '49300:9300'
      - '49200:9200'
volumes:
  esdata: